#!/bin/bash

# Map IDs in data.

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

REPOURL="https://github.com/cambridgeltl/uniprotidmap"
REPOGIT="git@github.com:cambridgeltl/uniprotidmap.git"
REPONAME="uniprotidmap"

DATADIR="$SCRIPTDIR/../data/converted"
IDMAP="$SCRIPTDIR/../../uniprotidmap/NCBIGENE-pr-idmapping.dat"

set -eu

echo $IDMAP
if [ ! -f "$IDMAP" ]; then
    cat <<EOF
ERROR: "$IDMAP" not found

ID mapping requires data generated by tools found in the repository
$REPOURL. Try the following:

    cd ..
    git clone $REPOGIT
    ./$REPONAME/REBUILD-DATA.sh
    cd -

EOF
    exit 1
fi

for d in $(find "$DATADIR" -depth 1 -type d); do
    echo "Mapping IDs in $d with $IDMAP ..." >&2
    python "$SCRIPTDIR/../tools/mapids.py" -r -v "$IDMAP" "$d"
    echo "Done mapping IDs in $d with $IDMAP" >&2
done
